version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    volumes:
      - mysqlvolume:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
       
volumes:
  mysqlvolume:
 
#java:
#  restart: on-failure
#networks:
#    default:
#        driver: custom-driver-1